from unittest import TestCase
long_line = "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfehgiuenguineiugbjqwbnijbvnqrijbnijeqnbijreqbnjgibrifgnqrwiugnriqbngihiugribnjnbjsdfnbjdsfnbjsfjdndddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"

class TestAlwaysPass(TestCase):
    def test_true_is_true(self):
        self.assertTrue(True)
